server:
  port: 8080
camel:
  springboot:
    name: ServicesRest
management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/twohump?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: mysqlAdmin123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
