server:
  port: 8080
camel:
  springboot:
    name: ServicesRest
dlwhitehurst:
  api:
    path: '/camel'
management:
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s